import { Talent } from "../../Classes";

const tier4 = [
  new Talent(
    "Elemental Impact",
    "spell_nature_unrelentingstorm",
    [
      "Your criticals from direct damage spells have a ",
      "% chance to activate Elemental Focus. In addition, your spell critical strike chance is increased by ",
      "% while Elemental Focus is active.",
    ],
    3,
    [
      [15, 30, 45],
      [2, 4, 6],
    ],
    [{ x: 2, y: 0 }],
    null,
    null,
    null,
    null,
    null,
    null,
    {
      isNew: true,
      isChanged: false,
      isMoved: false,
    }
  ),
  new Talent(
    "Eye of the Storm",
    "spell_nature_eyeofthestorm",
    [
      "Gives you a ",
      "% chance to gain the focused casting effect for 6 sec after being the victim of a melee or ranged critical strike. The focused casting effect prevents you from losing casting time when taking damage.",
    ],
    3,
    [[33, 66, 100]]
  ),
  null,
  new Talent(
    "Improved Fire Totems",
    "spell_fire_sealoffire",
    [
      "Reduces the delay before your Fire Nova Totem activates by ",
      " sec and reduces the threat generated by your Magma Totem by ",
      "%.",
    ],
    2,
    [
      [1, 2],
      [25, 50],
    ]
  ),
];

export default tier4;
