import { Talent } from "../../Classes";

const tier4 = [
  new Talent(
    "Improved Fire Totems",
    "spell_fire_sealoffire",
    [
      "Reduces the delay before your Fire Nova Totem activates by ",
      " sec and reduces the threat generated by your Magma Totem by ",
      "%.",
    ],
    2,
    [
      [1, 2],
      [25, 50],
    ]
  ),
  new Talent(
    "Eye of the Storm",
    "spell_nature_eyeofthestorm",
    [
      "Gives you a ",
      "% chance to gain the focused casting effect for 6 sec after being the victim of a melee or ranged critical strike. The focused casting effect prevents you from losing casting time when taking damage.",
    ],
    3,
    [[33, 66, 100]]
  ),
  null,
  new Talent(
    "Storm Surge",
    "spell_nature_regeneration_02",
    [
      "Reduces the penalty between jumps from your Chain Heal and Chain Lightning by ",
      "%.",
    ],
    3,
    [[25, 50, 75]],
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    { isChanged: false, isNew: true, isMoved: false }
  ),
];

export default tier4;
